clustering:
	python cluster_persistence_diagrams.py /links/groups/borgwardt/Projects/Ephemeral/Partly\ Cloudy/tda/masked/persistence_diagrams/
	python cluster_persistence_diagrams.py -m top_persistence /links/groups/borgwardt/Projects/Ephemeral/Partly\ Cloudy/tda/masked/persistence_diagrams/
